### ISSUE TITLE
Window Leak.

### ISSUE THREAD

**Issue by YYYSSSHHH** [billthefarmer/notes#19]
**The Stack Trace:**
[ 07-18 10:01:02.448  4505: 4505 E/WindowManager ]
android.view.WindowLeaked: Activity org.billthefarmer.notes.Notes has leaked window com.android.internal.policy.PhoneWindow$DecorView{f8eb0db V.E...... R....... 0,0-575,353} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at org.billthefarmer.notes.Notes.saveAsDialog(Notes.java:2202)
	at org.billthefarmer.notes.Notes.saveAs(Notes.java:2139)
	at org.billthefarmer.notes.Notes.onOptionsItemSelected(Notes.java:488)
	at android.app.Activity.onMenuItemSelected(Activity.java:2926)
	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
	at android.widget.AbsListView$3.run(AbsListView.java:3903)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

[ 07-18 10:01:16.267  4505: 4505 E/WindowManager ]
android.view.WindowLeaked: Activity org.billthefarmer.notes.Notes has leaked window android.widget.PopupWindow$PopupDecorView{63c158d V.E...... ......ID 0,0-294,720} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:658)
	at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:170)
	at android.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:997)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Maybe can be solved with reference to this:** https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

If you  confirm or solve  this problem, please tell me the cause of this phenomenon.

**Comment by billthefarmer** [comment]
See #18
